config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :palabras
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :imagens
  devise_for :users
  root 'home#index'

  post 'identificarme' => 'home#index', :as => 'identificarme'
  post 'elegir' => 'home#elegir', :as => 'elegir'
  post 'resultados' => 'home#resultados', :as => 'resultados'
  get 'resultados' => 'home#resultados'
  get 'reportes' => 'home#reportes'
  get 'reportes/:palabra' => 'home#reportes', :as => 'reportepalabra'

  #get 'home/buscar'
  #get 'home/elegir'
  #get 'home/resultados'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  require 'pry'

  def index
    @base_uri = JSON.load(open(%"https://www.googleapis.com/customsearch/v1?key=AIzaSyBjwXOLlY8-CPv_csamC9h5_N3lJr7P4Vw&cx=007331231350547501427:xk6qclo-fig&searchType=image&q=#{Palabra.all.sample.nombre}"))
    #@base_uri = JSON.load(open("q.json"))
  
  end

  def reportes
    if params[:palabra]
      @likes = Like.where(palabra: params[:palabra])
      @likes_f = JSON.load(open(%"https://alkanza-9b441.firebaseio.com/likes/#{params[:id]}.json"))

      @like_ma = Like.where(palabra: params[:palabra]).order(url: :desc).first
      @like_me = Like.where(palabra: params[:palabra]).order(url: :asc).last
    else
      @likes = Like.all
      @likes_f = JSON.load(open("https://alkanza-9b441.firebaseio.com/likes.json"))
      @like_ma = Like.order(url: :desc).first
      @like_me = Like.order(url: :asc).first#last
      #where(:user_id => current_user).order('finaliza desc')$
    end
  end

  def elegir
  	if params[:eleccion]
  		@like = Like.new(url: params[:eleccion], sitio: params[:sitio], palabra: params[:palabra], user_id: current_user.id)
  		@like.save

      base_uri = 'https://alkanza-9b441.firebaseio.com/'
      firebase = Firebase::Client.new(base_uri)
      response = firebase.push("likes", { url: params[:eleccion], sitio: params[:sitio], palabra: params[:palabra], user_id: current_user.id})
      #response.success? # => true
      #response.code # => 200
      #response.body # => { 'name' => "-INOQPH-aV_psbk3ZXEX" }
      #response.raw_body # => '{"name":"-INOQPH-aV_psbk3ZXEX"}'

  	end
  	redirect_to root_url
  end

  def resultados
  	if params[:username]
      if @usuario = User.find_by(:username => params[:username])
    		#@usuario = User.find_by(:email => params[:email])
    		@likes = Like.where(user_id: @usuario.id)
        @likes_f = JSON.load(open("https://alkanza-9b441.firebaseio.com/likes.json"))
        flash[:result] = %"Usuario tiene #{@likes.count}"
        flash[:color] = "success"
    	else
        flash[:result] = "No hay resultados de este usuario"
        flash[:color] = "danger"
    		@likes = Like.all
        @likes_f = JSON.load(open("https://alkanza-9b441.firebaseio.com/likes.json"))
    	end
    else
      @likes = Like.all
      @likes_f = JSON.load(open("https://alkanza-9b441.firebaseio.com/likes.json"))
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/elegir.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

app/views/home/index.html.erb
<center><h1>Palabra: <%= @base_uri['queries']['request'][0]['searchTerms'] %></h1></center>

<% @gs = @base_uri['items'].sample(2) %>  
 
 <div class="row">
  <center>
  <div class="col-md-2"></div>
  <% @gs.each do |item| %>
  <div class="col-md-4">
    <%=  link_to elegir_path(eleccion: item['link'], sitio: item['displayLink'], palabra: @base_uri['queries']['request'][0]['searchTerms']), method: :post do %>
        <img src="<%= item['link'] %>" alt="..." class="img-rounded" width="328" height="328">      
    <% end %>   
    </div>
  <% end %>
  <div class="col-md-2"></div>
  </center>
 </div>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-4"><center><h1>Me gusta A</h1></center></div>
  <div class="col-md-4"><center><h1>Me gusta B</h1></center></div>
  <div class="col-md-2"></div>
</div>

app/views/home/reportes.html.erb
<!--
<div class="col-md-12">
<% @like_ma.url %>
<img src="<%= @like_ma.url %>" alt="..." class="img-rounded" width="80" height="80">
<br>
<% @like_me.url %>
<img src="<%= @like_me.url %>" alt="..." class="img-rounded" width="80" height="80">
-->


<% like_contador_ma = Like.where(url: @like_ma.url).count %>
<br>
<% like_contador_me = Like.where(url: @like_me.url).count %>



          <!--
          <div class="row placeholders">
            <div class="col-md-1"></div>
            <div class="col-md-5 placeholder">
              <center><img src="<%= @like_ma.url %>" width="200" height="200" class="img-responsive img-circle" alt="Generic placeholder thumbnail">
              <h4>Mas elegida</h4>
              <span class="text-muted">Tiene: <%= like_contador_ma %> votos</span>
              </center>
            </div>
          
            <div class="col-md-5 placeholder">
              <center><img src="<%= @like_me.url %>" width="200" height="200" class="img-responsive img-circle" alt="Generic placeholder thumbnail">
              <h4>Menos elegida</h4>
              <span class="text-muted">Tiene: <%= like_contador_me %> votos</span>
              </center>
            </div>
            <div class="col-md-1"></div>
          </div>
          -->

          <!--<h2 class="sub-header">Section title</h2>-->
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Sitio</th>
                  <th>Url</th>
                  <th>Palabra</th>
                  <th>Usuario</th>
                </tr>
              </thead>
              <tbody>
               
                <% @likes.each do |like|%>
                <!--
                <tr>
                  <td><% like.id %></td>
                  <td><% like.sitio %></td>
                  <td>
                  	<img src="<%= like.url %>" alt="..." class="img-rounded" width="80" height="80">
                  </td>
                  <td><% link_to like.palabra, reportepalabra_path(like.palabra) %></td>
                  <td><% like.user.username %></td>
                </tr>
                -->
                <% end %>

                <tr><center><td><h1><center>Firebase</center></h1></td></center></tr> 
                <% @likes_f.each do |like|%>
                <tr>
                  <td><%= like[0] %></td>
                  <td><%= like[1]['sitio'] %></td>
                  <td>
                    <img src="<%= like[1]['url'] %>" alt="..." class="img-rounded" width="80" height="80">
                  </td>
                  <td><%= like[1]['palabra'] %></td>
                  <td><%= User.find(like[1]['user_id']).username %></td>
                </tr>
                <% end %>
                
              </tbody>
            </table>
          </div>
        </div>

app/views/home/resultados.html.erb
<center><h1>Resultados Generales</h1></center>

<center><h3><%= Like.all.count %> imagenes con like</h3></center>
<center><h3><%= @likes_f.count %> imagenes con like Firebase</h3></center>

<% if flash[:result] %>
	<center><div class="alert alert-<%= flash[:color] %>" role="alert"><%= flash[:result] %></div></center>
<% end %>

<br>
<%= form_tag(resultados_path) do %>
  <div class="col-lg-4"></div>
  <div class="col-lg-4">
    <div class="input-group" >
      <!--<input type="text" class="form-control" placeholder="Search for...">-->
      <%= text_field_tag :username, nil, :class => 'form-control', :placeholder => "username" %>
      <span class="input-group-btn">
        <!--<button class="btn btn-default" type="button">Go!</button>-->
        <%= submit_tag('Resultados', :class => "btn btn-default") %>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
  <div class="col-lg-4"></div>
<% end %>


<br>
<hr>
<center>
<% @likes.each do |like|%>
	<%= like.url %><br>
	cantidad de voto  o usuarios que les gusto <br>
	usuarios que voraron por esta imagen<br>
	corresponder al % por ciento de los votos<br>
	<hr>
<% end %>
</center>

<center><h1>Firebase</h1></center>

<center>
<% @likes_f.each do |like|%>
  <%= like[1]['url'] %><br>
  cantidad de voto  o usuarios que les gusto <br>
  usuarios que voraron por esta imagen<br>
  corresponder al % por ciento de los votos<br>
  <hr>
<% end %>
</center>