config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :palabras
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :imagens
  devise_for :users
  root 'home#index'

  post 'identificarme' => 'home#index', :as => 'identificarme'
  post 'elegir' => 'home#elegir', :as => 'elegir'
  post 'resultados' => 'home#resultados', :as => 'resultados'
  get 'resultados' => 'home#resultados'
  get 'reportes' => 'home#reportes'
  get 'reportes/:palabra' => 'home#reportes', :as => 'reportepalabra'

  #get 'home/buscar'
  #get 'home/elegir'
  #get 'home/resultados'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/palabra.rb
class Palabra < ApplicationRecord
end

app/controllers/palabras_controller.rb
class PalabrasController < ApplicationController
  before_action :set_palabra, only: [:show, :edit, :update, :destroy]

  # GET /palabras
  # GET /palabras.json
  def index
    @palabras = Palabra.all
  end

  # GET /palabras/1
  # GET /palabras/1.json
  def show
  end

  # GET /palabras/new
  def new
    @palabra = Palabra.new
  end

  # GET /palabras/1/edit
  def edit
  end

  # POST /palabras
  # POST /palabras.json
  def create
    @palabra = Palabra.new(palabra_params)

    respond_to do |format|
      if @palabra.save
        format.html { redirect_to @palabra, notice: 'Palabra was successfully created.' }
        format.json { render :show, status: :created, location: @palabra }
      else
        format.html { render :new }
        format.json { render json: @palabra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /palabras/1
  # PATCH/PUT /palabras/1.json
  def update
    respond_to do |format|
      if @palabra.update(palabra_params)
        format.html { redirect_to @palabra, notice: 'Palabra was successfully updated.' }
        format.json { render :show, status: :ok, location: @palabra }
      else
        format.html { render :edit }
        format.json { render json: @palabra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /palabras/1
  # DELETE /palabras/1.json
  def destroy
    @palabra.destroy
    respond_to do |format|
      format.html { redirect_to palabras_url, notice: 'Palabra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_palabra
      @palabra = Palabra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def palabra_params
      params.require(:palabra).permit(:nombre)
    end
end

app/helpers/palabras_helper.rb
module PalabrasHelper
end

app/views/palabras/_form.html.erb
<%= form_with(model: palabra, local: true) do |form| %>
  <% if palabra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(palabra.errors.count, "error") %> prohibited this palabra from being saved:</h2>

      <ul>
      <% palabra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :palabra_nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/palabras/edit.html.erb
<h1>Editing Palabra</h1>

<%= render 'form', palabra: @palabra %>

<%= link_to 'Show', @palabra %> |
<%= link_to 'Back', palabras_path %>

app/views/palabras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Palabras</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @palabras.each do |palabra| %>
      <tr>
        <td><%= palabra.nombre %></td>
        <td><%= link_to 'Show', palabra %></td>
        <td><%= link_to 'Edit', edit_palabra_path(palabra) %></td>
        <td><%= link_to 'Destroy', palabra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Palabra', new_palabra_path %>

app/views/palabras/new.html.erb
<h1>New Palabra</h1>

<%= render 'form', palabra: @palabra %>

<%= link_to 'Back', palabras_path %>

app/views/palabras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @palabra.nombre %>
</p>

<%= link_to 'Edit', edit_palabra_path(@palabra) %> |
<%= link_to 'Back', palabras_path %>